/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_inventale_coregistration_survey_providers_fm_XlearnPredictor */

#ifndef _Included_com_inventale_coregistration_survey_providers_fm_XlearnPredictor
#define _Included_com_inventale_coregistration_survey_providers_fm_XlearnPredictor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_inventale_coregistration_survey_providers_fm_XlearnPredictor
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_inventale_coregistration_survey_providers_fm_XlearnPredictor_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_inventale_coregistration_survey_providers_fm_XlearnPredictor
 * Method:    predict
 * Signature: ([I[I[II)[Lcom/inventale/coregistration/survey/providers/fm/PredictionResult;
 */
JNIEXPORT jobjectArray JNICALL Java_com_inventale_coregistration_survey_providers_fm_XlearnPredictor_predict
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint);

/*
 * Class:     com_inventale_coregistration_survey_providers_fm_XlearnPredictor
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_inventale_coregistration_survey_providers_fm_XlearnPredictor_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
