/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_inventale_coregistration_survey_providers_fm_XlearnTrainer */

#ifndef _Included_com_inventale_coregistration_survey_providers_fm_XlearnTrainer
#define _Included_com_inventale_coregistration_survey_providers_fm_XlearnTrainer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_inventale_coregistration_survey_providers_fm_XlearnTrainer
 * Method:    train
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_inventale_coregistration_survey_providers_fm_XlearnTrainer_train
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_inventale_coregistration_survey_providers_fm_XlearnTrainer
 * Method:    predict
 * Signature: ([Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_inventale_coregistration_survey_providers_fm_XlearnTrainer_test
        (JNIEnv *, jobject, jobjectArray);


char** getArgs(JNIEnv *, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
